spring:
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: root
      password: root
server:
  servlet:
    session:
      timeout: 1m